services:
  streamlit_app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env/network.env
    environment:
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: always
